name: Release

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g truffle
    - run: npm install
    - run: truffle compile
    - run: echo "ETH_ROPSTEN_RPC=${{ secrets.ROPSTEN_NODE_URL }}" >> .env
    - run: echo "ETH_PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
    - run: echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env
    - run: truffle migrate --network ropsten
    - run: truffle run verify Counter --network ropsten
    - run: rm .env
